name: ar_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  ar_flutter_plugin:
    git: "https://github.com/Moovency/ar_flutter_plugin"
  flutter:
    sdk: flutter
  flutter_archive: ^6.0.3
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  vector_math: ^2.1.4

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - Images/
